#! /usr/bin/env python

from tqdist import quartet_distance
from sys import argv

with open(argv[1],'r') as f:
    tree1 = f.read().strip()

with open(argv[2],'r') as f:
    tree2 = f.read().strip()

print('\t'.join(str(x) for x in quartet_distance(tree1,tree2)))
 
